apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-deployment
  template:
    metadata:
      labels:
        app: db-deployment
    spec:
      volumes:
        - name: db-data
          emptyDir: {}
      containers:
      - name: db
        image: postgres:9.4
        env:
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/postgresql/data
