apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis-deployment
spec:
  selector:
    app: redis-deployment
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
